### ISSUE TITLE
SetView() should not be canceled on worker ctx when called from onElected

### ISSUE THREAD

**Issue by IdoZilberberg** [orbs-network/lean-helix-go#74]
See log:
https://circleci.com/gh/orbs-network/orbs-network-go/18853#tests/containers/2

In the log (see around timestamp `07:52:14.816909`) we see the following:
* The node which is the would-be-leader of V=5 (it is still on V=4) gets the last (5th) VIEW_CHANGE message of V=5 that will allow it to become leader of V=5.
* Mainloop writes this VIEW_CHANGE to the worker's message channel.
* Election trigger event on that node increments it to V=5 and cancels workerCtx that is attached to the last VIEW_CHANGE message.
* Workerloop reads that VIEW_CHANGE message from message channel, and because it is the 5th out of 5 required VIEW_CHANGE message, it calls onElectedByViewChange(ctx) where ctx is the *now canceled* context, that was attached to the VIEW_CHANGE message.
* onElectedByViewChange() calls SetView(ctx). 
* SetView() should have sent NEW_VIEW, informing other nodes of this block, but because ctx is cancelled, SetView() does not send NEW_VIEW, and the leader node does nothing more, wasting the view.

Possible solution:
- Cancel the worker context only in SetView() (and not in Election trigger) thus asserting that its semantic role is that of a View context. This would prevent the automatic and incorrect cancelation of the context upon Election trigger. SetView() is called both by Election Trigger and by onElectedByViewChange() so its a good place to decide whether the worker context should be canceled. The downside:  this will leak the worker context to the Workerloop.

Shai thinks the worker context should be a View context - this is, it should be cancelled on every view increment anyway.

@gadcl @ronnno @electricmonk

**Comment by ronnno** [comment]
If I understand @electricmonk 's suggestion we are talking about storing a `map[HeightView]Context`?... This makes a lot of sense to me

**Comment by electricmonk** [comment]
well, IMO you can hold a `map[HeightView]CancelFunc` but you shouldn't hold a context

**Comment by electricmonk** [comment]
also a map will have shared state and require a mutex

**Comment by electricmonk** [comment]
I think the `SharedState` needs to hold the current `CancelFunc` and call it on view change.

**Comment by electricmonk** [comment]
and if `SetView` is called with the background context, it can create a new worker context from it, if it's required

**Comment by ronnno** [comment]
I think this would work - it means though that we ditch the idea that only the main loop cancels contexts and instead move the cancellation to occur under mutex in the `SharedState` object. This way we can effectively split the context of the worker thread whenever it progresses in the term into two - before the increment of height/view and after. the calling code would have two contexts. 

I don't think it should happen when we pass the background context, it should happen whenever we change the `HeightView` value. 

Logically it's equivalent to holding a `map[HeightView]Context` but cleaner on the memory, and more idiomatic. I like this.

**Comment by ronnno** [comment]
@electricmonk  i want to understand what you're suggesting because if I understand it correctly it will not solve this bug.
`map[HeightView]CancelFunc` is logically equivalent to `map[HeightView]Context` with some restrictions on where the context is created and its pointers stored (stack - not heap). this is cleaner, more idiomatic coding but i'm not sure it's flexible enough to bypass this race condition.

the problem with this approach is that main-loop will never know of a context change if the worker loop changes the view. therefore a map to context is required so that main-loop would be able to retrieve the correct context based on the current view.

I know this is not idiomatic but it makes reasoning much easier. lets discuss?

**Comment by electricmonk** [comment]
yeah, f2f

**Comment by ronnno** [comment]
to summarize the talk (@electricmonk , @ronnno ): `SetView()` is always called downstream of the main loops in the call-stack. if it allocates a new context this context will need to be passed back up to the top level loop for the next iteration to propagate the same context downstream again. this is not easy to do if we don't keep the pointer to the context.

However, a possible solution is to allocate a new context at the top level loop on every new iteration of the worker thread. this allows us to replace the context midway and still maintain only a reference to the `CancelFunc` in the shared state.  

That said, we also agreed that since it's not clear where the how this will resolve the issue first step should be to reproduce the issue in a test

**Comment by IdoZilberberg** [comment]
Meeting minutes 10-Sep-19 (Ron, Ido, Gad):
Gad and OdedW feel this fix is not important because it does not affect safety of LH.
We came up with 3 options to handle this:

1) Ease the conditions of the test so it will not fail. Don't make any changes to lean-helix.
2) Add the context itself to workerloop struct and let the workerloop decide when to cancel it. In the case described above, the workerloop would have known that the call to SetView() was legit and should not have been cancelled.
3) Move the responsibility for creating the worker context to the workerloop. The workerloop will create a new context just before passing it to a long-running operation, and publish its cancel() func in the shared state. The mainloop will call the cancel() func on election and nodesync as today. Shared state will also hold the latest H/V that was canceled so that requests coming in with earlier H/V would not call on long ops (or call them with a canceled context). This last part is an optimization.

My intuition is that it we should first consider (1) and then (3).

**Comment by electricmonk** [comment]
The failing test wasn’t any specific test. It’s the timeout of the acceptance test. Currently it’s 10 seconds. Do you suggest to increase it?

Shai

________________________________

**Comment by ronnno** [comment]
@electricmonk  yes, we suggest to be more lenient in timeouts.
@IdoZilberberg I'm not sure option 2 what I understood in the talk - I would say - the mainloop cancels the context as it does today, but when the mainloop cancels (and replaces) the worker context it would also "register" it with the `SharedState` object. When the worker thread tries to move into the currently active view (and height) *with a cancelled context*, and at the same time `SharedState`  knows of a newer context which is still uncanceled it will "upgrade" the caller's context by not failing the call and instead returning the new context. the caller will continue running with the newly returned context.
This would be done both in the race scenario of `VIEW_CHANGE/Election trigger` and `Sync/Commit`

**Comment by ronnno** [comment]
please see branch `issue/74` and pr #75 for bug reproduction.
